### ISSUE TITLE
creates/kit/pocetni iteme

### ISSUE THREAD

**Issue by Lukaac123** [Games4k/4kGamesIssues#10]
### Issue description
dodati crates na skyblock/dododati kitove/pocetne iteme kad se sponuju
### Core information
**Server**: skyblock

**MC verzija na kojoj si**: insert

**Plugin koji ne radi**: (ako ne znas koji je ne pisi nista)

- [x] kit

- [x] Pocetni itemi

- [x] Crates

**Comment by Games4k** [comment]
Vote/Votifier prebaciti u drugi issue
