### ISSUE TITLE
Bug sa inventarom u creative modu

### ISSUE THREAD

**Issue by TeljeJedno** [Games4k/4kGamesIssues#39]
### Issue description
Kada se u inventaru u creative modu drzi shift i klikne iks kako bi se obrisale sve stvari, nista se ne desava. Sve se stvari vracaju umesto samo onih koji moraju da budu u inventaru poput server selectora,gadget-a itd....

### Core information
**Server**: lobby
**MC verzija na kojoj si**: 1.8.9

**Plugin koji ne radi**: (ako ne znas koji je ne pisi nista)

**Comment by Games4k** [comment]
Greska nece biti resena, vrlo je nebitna sa obzirom da niko od igraca nema Creative mode. Sta vise, nije preporuceno da se u opste prebacujes u gmc na lobby serverima.
