### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by Lukaac123** [Games4k/4kGamesIssues#44]
**Opisi sta zelis da dodamo i zasto**
Dodati plugin za custom enchant i da drveca padaju cela ako se srusi samo jedan blok

**Imas li neke plugine koji bi takodje trebali biti dodati da bi se ovo dodalo?**
insert

**Dodatne informacije**
insert

**Comment by Games4k** [comment]
Moved to https://gitlab.com/OpenSource02/4kGamesNetwork/issues/3
